### PR TITLE
Don't reupload cache on every build

### PR DESCRIPTION
**Pull request by abitrolly**
Upstream issue - https://github.com/travis-ci/docs-travis-ci-com/issues/358

### CODE REVIEW

**Comment by abitrolly** [comment]
@IRus need one more commit to use cache without files that were removed as a result of this commit.

Looks like we will also need to remove these files. What `caches-4.0.1` is for:

    /home/travis/.gradle/caches/4.0.1/fileHashes/fileHashes.bin
    /home/travis/.gradle/caches/4.0.1/fileHashes/fileHashes.lock

**Comment by IRus** [comment]
@abitrolly `caches/4.0.1` is cache for gradle 4.0.1. We can try delete this files:

```
$HOME/.gradle/caches/*/fileHashes/
```

**Comment by abitrolly** [comment]
The presence of files that constanltly change in caches looks like a bug.

**Comment by IRus** [comment]
Just make another commit to check assumptions about fileHashes directory.

**Comment by abitrolly** [comment]
:+1:

**Pull request merged**
